fix set-secrets and list-secrets scripts

diff --git a/scripts/set-secrets b/scripts/set-secrets
--- a/scripts/set-secrets
+++ b/scripts/set-secrets
@@ -2,15 +2,18 @@
 
 SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")";
 ROOT_DIR="$(dirname "$SCRIPT_DIR")";
+SECRETS_PATH="$ROOT_DIR/secrets.json";
 
-set-project-secrets() {
-  if [[ -f "$ROOT_DIR/secrets.json" ]]; then
-    cat "$ROOT_DIR/secrets.json" | dotnet user-secrets set --project "$1";
-  fi;
-}
+if [[ ! -f "$SECRETS_PATH" ]]; then
+  echo "Could not find secrets.json"
+  exit 1;
+fi;
+secrets="$(cat "$SECRETS_PATH")"
 
-set-project-secrets \
-  "$ROOT_DIR/test/Ozds.Elasticsearch.Test/Ozds.Elasticsearch.Test.csproj"
-
-set-project-secrets \
-  "$ROOT_DIR/src/Ozds.Web/Ozds.Web.csproj"
+for project in \
+    "$ROOT_DIR/test/Ozds.Elasticsearch.Test/Ozds.Elasticsearch.Test.csproj" \
+    "$ROOT_DIR/src/Ozds.Web/Ozds.Web.csproj" \
+    ; do
+  dotnet user-secrets clear --project "$project";
+  echo "$secrets" | dotnet user-secrets set --project "$project";
+done
